# Ubuntu 14.04 Trusty support
sudo: false
dist: trusty

language: cpp

compiler:
  - clang

addons:
  apt:
    sources:
    # add PPAs with more up-to-date toolchains
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.6
    - kalakris-cmake
    packages:
    # install toolchains
    - gcc-5
    - g++-5
    - clang-3.6
    - cmake
    # install boost
    - libboost1.55-all-dev
    
script:
  - mkdir build
  - cd build
  - mkdir debug
  - mkdir release
  - cd debug
  - cmake ../.. -DCMAKE_BUILD_TYPE=debug
  - make
  - cd ../release
  - cmake ../.. -DCMAKE_BUILD_TYPE=release
  - make
